# Generated by Django 5.2.7 on 2026-04-04 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='workstation',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
