# DEV IMAGE BUILD
FROM python:3.12-slim

WORKDIR /app


COPY poetry.lock pyproject.toml /app/

RUN pip install poetry==2.2.1
RUN poetry install

COPY runserver.sh /app/

RUN chmod +x /app/runserver.sh

COPY . /app/

EXPOSE 8000

CMD ["/app/runserver.sh"]
