# Generated by Django 5.2.7 on 2026-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_providerqualificationsmodel_branchmanageraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanageraccount',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facilitymanageraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
