# Generated by Django 5.2.7 on 2026-02-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_branchmanageraccount_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchmanageraccount',
            old_name='active',
            new_name='is_active',
        ),
    ]
