# Generated by Django 5.2.7 on 2026-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_rename_active_branchmanageraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovideraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
