# Generated by Django 5.2.7 on 2026-03-14 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('identity', '0005_healthcareprovideraccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('veri_identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workstations', models.ManyToManyField(blank=True, related_name='workstations', to='facility.workstation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
