# Generated by Django 5.2.7 on 2026-06-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_authcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientaccount",
            name="allergies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allergy strings e.g. ['Penicillin', 'Latex']",
            ),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="insurances",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Insurance providers the patient is covered under e.g. ['NHIF', 'AAR']",
            ),
        ),
        migrations.AddField(
            model_name="patientaccount",
            name="patient_uid",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="healthcareprovideraccount",
            name="licence_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="healthcareprovideraccount",
            name="licence_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="healthcareprovideraccount",
            name="practice_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
