# Generated by Django 5.2.7 on 2026-06-28 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0007_prescription_patient_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcareprovider",
            name="business_reg_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="business_reg_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="clinic_logo_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="cr12_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="extra_credentials",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of additional credentials e.g. [{'id': '...', 'name': 'KMPDB', 'number': '...', 'image_url': '...'}]",
            ),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="kra_pin",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="kra_pin_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="national_id_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="national_id_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="operating_licence",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="operating_licence_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="valid_licence_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="healthcareprovider",
            name="valid_licence_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient_identity",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked automatically by matching patient_email to an Identity at creation time. May be null for older records until the backfill command links them.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
