# Generated by Django 5.2.7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0008_healthcareprovider_business_reg_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcareprovider",
            name="subspecialties",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
