# Generated by Django 5.2.7 on 2026-06-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0009_healthcareprovider_subspecialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcareprovider",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
