# Generated by Django 6.0.7 on 2026-07-11 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kmpdc_facility_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sha_facility_code', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_type', models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('ER', 'Emergency')], max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='hmis.facility')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hmis.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(choices=[('cash', 'Cash'), ('sha', 'SHA (Social Health Authority)'), ('private_insurance', 'Private Insurance')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('line_items', models.JSONField(default=list)),
                ('claim_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hmis.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hmis.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hmis.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='hmis.patient'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('admin', 'Facility Admin'), ('receptionist', 'Receptionist')], max_length=20)),
                ('kmpdc_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hmis.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmis_staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('insurance', 'Insurance')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hmis.invoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='hmis.staff')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='attending_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='hmis.staff'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_system', models.CharField(default='http://hl7.org/fhir/sid/icd-10', help_text='URI of the coding system, e.g. ICD-10.', max_length=100)),
                ('code', models.CharField(help_text="e.g. 'I10' for essential hypertension", max_length=20)),
                ('display', models.CharField(help_text='Human-readable description of the code', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='hmis.encounter')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_recorded', to='hmis.staff')),
            ],
            options={
                'ordering': ['-is_primary', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('vitals', 'Vital Signs'), ('progress', 'Progress Note'), ('nursing', 'Nursing Note'), ('discharge_summary', 'Discharge Summary')], max_length=30)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('free_text', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='hmis.encounter')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to='hmis.staff')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['facility', 'last_name', 'first_name'], name='hmis_patien_facilit_0236de_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='hmis_patien_nationa_2552ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('facility', 'patient_number')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('facility', 'user')},
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'patient', '-start_datetime'], name='hmis_encoun_facilit_c1c205_idx'),
        ),
    ]
