# Generated by Django 6.0.7 on 2026-07-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('hmis', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='clinicalnoteaddendum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='clinicalnoteaddendum',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='hmis.clinicalnote'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='identity.patientaccount'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='Provider/staff who formally closed out the encounter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='facility.facility'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='identity.patientaccount'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='facility.workstation'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facility.facility'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='identity.patientaccount'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hmis.invoice'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_placed', to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='hmis.laborder'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_reviewed', to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='prescribed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.healthcareprovideraccount'),
        ),
        migrations.AddField(
            model_name='patientrecordaccesslog',
            name='accessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientrecordaccesslog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='identity.patientaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='hmis.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hmis.encounter'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-scheduled_at'], name='hmis_encoun_patient_d23584_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'status'], name='hmis_encoun_facilit_86a6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecordaccesslog',
            index=models.Index(fields=['patient', '-accessed_at'], name='hmis_patien_patient_02e9f1_idx'),
        ),
    ]
