# Generated by Django 5.2.7 on 2026-06-28 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_providerappointment_patient_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentcapture",
            name="form_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot of the form sections at the time of capture, so data remains readable even if the form is later edited or deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="providerappointment",
            name="patient_identity",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked automatically by matching patient_email to an Identity at booking time. May be null for older records until the backfill command links them.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="providerappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("in-progress", "In-progress"),
                    ("completed", "Completed"),
                    ("rescheduled", "Rescheduled"),
                    ("cancelled", "Cancelled"),
                    ("no-show", "No-show"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
