# Generated by Django 5.2.7 on 2026-06-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_f533ae_idx",
            old_name="notifications_recipient_read_idx",
        ),
    ]
